### Site metadata

title: Jekyll Bootstrap Quickstart
description: Starter template for using Jekyll 4 and the Bootstrap gem - with GitHub Actions

### Build settings

url: https://michaelcurrin.github.io
baseurl: /jekyll-bootstrap-quickstart

sass:
  load_paths:
    - _sass
    - vendor/bundle/ruby/3.0.0/gems/

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - LICENSE
  - README.md
  - sample.png
